# Base image Python yang ringan
FROM python:3.10-slim
# Set working directory
WORKDIR /app
# Copy daftar dependensi Python
COPY requirements.txt .
# Install dependensi Python
RUN pip install --no-cache-dir -r requirements.txt
# Copy seluruh kode backend (file .py, geojson, tif, dll)
COPY . .
# Cloud Run akan memberikan variabel environment $PORT.
# Script api_server.py sudah diatur untuk membacanya.
CMD ["python", "api_server.py"]
